const PRODUCTS = [
  {
    id: 1,
    name: "Headphones",
    price: 25000,
    category: "Electronics",
    image: "images/head-phones.png",
    stock: 12,
  },
  {
    id: 2,
    name: "Power bank",
    price: 10000,
    category: "Electronics",
    image: "images/powerbank.png",
    stock: 8,
  },
  {
    id: 3,
    name: "Charger",
    price: 5000,
    category: "Electronics",
    image: "images/charger.png",
    stock: 2,
  },
  {
    id: 4,
    name: "Phone case",
    price: 4000,
    category: "Electronics",
    image: "images/phone-case.png",
    stock: 2,
  },
  {
    id: 5,
    name: "Earpods",
    price: 5000,
    category: "Electronics",
    image: "images/earpods.png",
    stock: 2,
  },
  {
    id: 6,
    name: "Extension",
    price: 5000,
    category: "Electronics",
    image: "images/extension.png",
    stock: 2,
  },
  {
    id: 7,
    name: "Modem",
    price: 5000,
    category: "Electronics",
    image: "images/router.png",
    stock: 2,
  },
   {
    id: 8,
    name: "Tablet case",
    price: 5000,
    category: "Electronics",
    image: "images/tablet-case.png",
    stock: 2,
  },
];
const formatPrice = (n) => `₦${n.toLocaleString()}`;
